apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: postgresql:apps/Deployment:postgresql/h1v2
  labels:
    app: h1v2
  name: h1v2
  namespace: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h1v2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: h1v2
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password01
          image: quay.io/klaj2210/postgres:v1
          name: postgres
          ports:
            - containerPort: 5432
      serviceAccountName: useroot
